"""empty message

Revision ID: 32cd779c7bc0
Revises: 3e862d14b7ed
Create Date: 2017-02-17 00:59:53.413052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cd779c7bc0'
down_revision = '3e862d14b7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
