"""empty message

Revision ID: 3d1432f1fef1
Revises: d2dda16b373a
Create Date: 2017-02-17 00:30:15.455509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1432f1fef1'
down_revision = 'd2dda16b373a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'projects', sa.Column('budget_id', sa.Integer(), nullable=True))
    op.add_column(u'projects', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column(u'projects', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column(u'projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.drop_column(u'projects', 'start_month_period')
    op.drop_column(u'projects', 'end_month_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'projects', sa.Column('end_month_period', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column(u'projects', sa.Column('start_month_period', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column(u'projects', 'start_date')
    op.drop_column(u'projects', 'priority')
    op.drop_column(u'projects', 'end_date')
    op.drop_column(u'projects', 'budget_id')
    op.drop_table('departments')
    op.drop_table('periods')
    op.drop_table('company')
    # ### end Alembic commands ###
