"""empty message

Revision ID: 3e862d14b7ed
Revises: f31ebe0b36c5
Create Date: 2017-02-17 00:55:52.357425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e862d14b7ed'
down_revision = 'f31ebe0b36c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'departments_head_id_fkey', 'departments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'departments_head_id_fkey', 'departments', 'users', ['head_id'], ['id'])
    # ### end Alembic commands ###
