"""empty message

Revision ID: 4838f48b65a4
Revises: cec14320cd40
Create Date: 2017-02-28 01:20:59.238543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4838f48b65a4'
down_revision = 'cec14320cd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_mapping')
    op.drop_constraint(u'departments_head_id_fkey', 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_id')
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_task')
    op.drop_column('tasks', 'description')
    op.add_column('departments', sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'departments_head_id_fkey', 'departments', 'users', ['head_id'], ['id'])
    op.create_table('task_mapping',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], [u'tasks.id'], name=u'task_mapping_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], [u'tasks.id'], name=u'task_mapping_parent_id_fkey')
    )
    # ### end Alembic commands ###
