"""empty message

Revision ID: 521e219e8264
Revises: 32cd779c7bc0
Create Date: 2017-02-22 21:09:18.881954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521e219e8264'
down_revision = '32cd779c7bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'percent')
    # ### end Alembic commands ###
