"""empty message

Revision ID: e6aec46c70eb
Revises: 4838f48b65a4
Create Date: 2017-02-28 02:25:54.003198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6aec46c70eb'
down_revision = '4838f48b65a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'percent')
    # ### end Alembic commands ###
